import type { CSSProperties } from "react";
import {
  PANE_CHEVRON_TRANSITION,
  PANE_DISCLOSURE_TRANSITION,
  PANE_TOOLBAR_CHIP_BORDER,
  PANE_TOOLBAR_CHIP_FILL,
  PANE_TOOLBAR_DROPDOWN_MIN_WIDTH,
  PANE_TOOLBAR_ICON_SIZE,
  PANE_TOOLBAR_ITEM_HEIGHT,
  PANE_TOOLBAR_ITEM_RADIUS,
  paneToolbarButtonBase,
} from "../pane/paneStyles";

export const TOOLBAR_ITEM_HEIGHT = PANE_TOOLBAR_ITEM_HEIGHT;
export const TOOLBAR_ITEM_RADIUS = PANE_TOOLBAR_ITEM_RADIUS;
export const TOOLBAR_ICON_SIZE = PANE_TOOLBAR_ICON_SIZE;
export const TOOLBAR_DROPDOWN_MIN_WIDTH = PANE_TOOLBAR_DROPDOWN_MIN_WIDTH;
export const TOOLBAR_CHIP_FILL = PANE_TOOLBAR_CHIP_FILL;
export const TOOLBAR_CHIP_BORDER = PANE_TOOLBAR_CHIP_BORDER;
export const TOOLBAR_CHEVRON_TRANSITION = PANE_CHEVRON_TRANSITION;
export const TOOLBAR_DISCLOSURE_TRANSITION = PANE_DISCLOSURE_TRANSITION;

export function toolbarButtonBaseStyle(disabled = false): CSSProperties {
  return paneToolbarButtonBase(disabled);
}
